### ISSUE TITLE
CA certificates adding without restarting of JVM

### ISSUE THREAD

**Issue by mikhail-yarosh** [JetBrains/teamcity-kubernetes-plugin#16]
We need mechanism for adding SSL-certificates to Authentication strategy by username/password without restarting of JVM.
Sometimes, kubernetes cluster haven't mechanisms for using prepared ssl-certs for securing https session for kubectl, and generate such certificates automatically. So we need to add them to JVM's cacerts and restart the teamcity-server. It takes too long and affects all the services and users.

**Comment by ekoshkin** [comment]
Make sense.

**Comment by ekoshkin** [comment]
Plugin uses fabric8 k8s java client. So this issue should be solved setting env variable KUBERNETES_TRUST_CERT=true.
Related fabric8 issue https://github.com/fabric8io/fabric8/issues/4276

**Comment by ketchoop** [comment]
Little addition: now the name of the variable, that can fix this issue is KUBERNETES_TRUST_CERTIFICATES.
