### ISSUE TITLE
Certificate authentication with kubernetes server

### ISSUE THREAD

**Issue by mayusuk** [JetBrains/teamcity-kubernetes-plugin#17]
Hi,

I am trying out the plugin to integrate teamcity server with kubernetes server but i couldn't authenticate with CA certificate. 

Error-

Error connecting: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Do we need to add the certificate to JVM certs?

**Comment by ketchoop** [comment]
Related issue: https://github.com/JetBrains/teamcity-kubernetes-plugin/issues/16

**Comment by ekoshkin** [comment]
Plugin uses fabric8 k8s java client. So this issue should be solved setting env variable KUBERNETES_TRUST_CERT=true.
Related fabric8 issue https://github.com/fabric8io/fabric8/issues/4276

**Comment by mayusuk** [comment]
After setting the env variable, I was able to go further but now I am getting the unauthorised error. We just need to add the content of client.crt  while configuring the plugin right?

**Comment by ekoshkin** [comment]
Yes, should work that way. If not please share the actual error message with stacktrace.

**Comment by mayusuk** [comment]
thanks, solved the issue. Forgot to add the certificate key to teamcity
