### ISSUE TITLE
missing images in the blog post

### ISSUE THREAD

**Issue by epishkin** [JetBrains/teamcity-kubernetes-plugin#18]
https://blog.jetbrains.com/teamcity/2017/10/teamcity-kubernetes-support-plugin/
Some images in this article are not displayed. All broken URLs look like this `https://blog.jetbrains.com/teamcity/2017/10/teamcity-kubernetes-support-plugin/null`.

**Comment by ekoshkin** [comment]
Strange. Just tried to visit all the links. Work for me. What particular links are not working for you?

**Comment by epishkin** [comment]
Try to open in Safari. I think this is how html is written.
Safari view: 
![screen shot 2017-11-17 at 6 04 56 pm](https://user-images.githubusercontent.com/448794/32972772-06ad4c6a-cbc2-11e7-8279-03bc64653852.png)

Html view:
![screen shot 2017-11-17 at 6 05 39 pm](https://user-images.githubusercontent.com/448794/32972782-1403702e-cbc2-11e7-8c58-6a8b34e271c9.png)

**Comment by yegnau** [comment]
Thanks for noticing! Indeed, the `null` images were the problem. It's fixed now.

**Comment by epishkin** [comment]
thanks for fixing!
