### ISSUE TITLE
java.security.cert.CertPathValidatorException: signature check failed

### ISSUE THREAD

**Issue by cj-anthony** [JetBrains/teamcity-kubernetes-plugin#19]
Hi, I'm trying to get this up and running with a kubernetes cluster running out of Azure Container Services. When testing the connection with a username and password I get this error:

Error connecting to https://xxx.centralus.azmk8s.io: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed

I also get this warning on the TeamCity server when I try to test the connection.

WARN - netes.client.internal.SSLUtils - SSL handshake failed. Falling back to insecure connection.

When I browse to the url I get an invalid cert authority error, I assume because in this case kubernetes is it's own CA and the certificate it has generated is not trusted. KUBERNETES_TRUST_CERT is set to "true" on the team city server.

Am I configuring this plugin incorrectly? Is there something about how this is set up that I don't understand? Do I need to somehow download the cert from kubernetes and get TeamCity to trust it?

**Comment by ekoshkin** [comment]
Hi, @cj-anthony 
You should doanload the cerificate and use it in kubernetes cloud profile auth strategy setting
