### ISSUE TITLE
Token Authentication strategy - Password too long error

### ISSUE THREAD

**Issue by omeryesil** [JetBrains/teamcity-kubernetes-plugin#20]
Validation error occurs when token is entered for Token Authentication strategy. To reproduce
- Select Token as Authentication strategy
- Enter the Token (in my case it is 120 characters long)
- Click on Save
  -Error pops up: `The password is too long. Entered password length is 120 characters. Please shorten the password.`

**Comment by renperez** [comment]
any update on this? I am getting the same error

**Comment by ekoshkin** [comment]
By the way, what kubernetes provider do you use? Google cloud?

**Comment by MikePennington** [comment]
I'm getting this same error. I'm using Google Cloud.
