### ISSUE TITLE
How do I generate kubernetes credentials (token/cert/passwd) for teamcity when k8s cluster runs on Azure

### ISSUE THREAD

**Issue by yfried** [JetBrains/teamcity-kubernetes-plugin#23]
I have a new Kubernetes cluster, but I can't figure out how to generate credentials for TeamCity. Can you please help?

**Comment by ekoshkin** [comment]
It depends on how you got that cluster. Google cloud, on premices setup or AWS EKS, etc?

**Comment by yfried** [comment]
It's on Azure. Created by acs-engine

**Comment by ekoshkin** [comment]
So client certificates are not working https://github.com/Azure/AKS/issues/64

**Comment by ekoshkin** [comment]
You can follow connection instructions in Azure portal.
After you will export credentials go to k8s config and use credentials stored in it.
