### ISSUE TITLE
Timeout missing for "cloud profiles" menu

### ISSUE THREAD

**Issue by mikhail-yarosh** [JetBrains/teamcity-kubernetes-plugin#31]
i have a connected to Teamcity kubernetes cluster.
So trouble is:
1) Remove the cluster
2) try to open root project - > cloud profiles
3) enjoy the timeout missing

**Comment by ekoshkin** [comment]
@mikhail-yarosh sorry, i did not understand the idea of the issue
could you please rephrase

**Comment by paksv** [comment]
Closed as I was unable to reproduce
