### ISSUE TITLE
Don't see option for custom pod template

### ISSUE THREAD

**Issue by nchidipothu** [JetBrains/teamcity-kubernetes-plugin#34]
Hi Support,

We recently upgraded plugin from snapshot-20180213190929 to snapshot-20180430143803

But we don't see option for "custom pod template"

Can you please help us.

Thanks,
Naresh Ch

**Comment by ekoshkin** [comment]
Find fixed plugin here https://plugins.jetbrains.com/plugin/download?rel=true&updateId=48894
