### ISSUE TITLE
DinD builds

### ISSUE THREAD

**Issue by voron** [JetBrains/teamcity-kubernetes-plugin#36]
Now I get 
```
[Step 1/1] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
while using `Docker` runner type with teamcity k8s agent. Is it possible to use docker builds with teamcity agent inside k8s ?

**Comment by ekoshkin** [comment]
It is possible. Make sure container with build agent is running in privileged mode.

**Comment by voron** [comment]
>Make sure container with build agent is running in privileged mode.

How should I do this while container with build agent i created by teamcity-kubernetes-plugin ?

**Comment by ekoshkin** [comment]
@voron both solutions looks good to me. Thank you for sharing those snipets!
