### ISSUE TITLE
Agents showing up in wrong agent pools

### ISSUE THREAD

**Issue by dchw** [JetBrains/teamcity-kubernetes-plugin#39]
I have a three separate cloud profiles, each depending on separate pod specs (each used from a separate named deployment), and each is only set to be in a particular agent pool. The pods and deployments are all in the same namespace `teamcity`. Each also has a unique agent name prefix associated with it.

However, two of my pools are getting confused and will list each others pods in the Agents -> Cloud tab. Here is a screenshot of it happening:

![image](https://user-images.githubusercontent.com/1056816/46089967-ea84ca80-c16c-11e8-8e8a-534b30b4f9c6.png)

I am on TeamCity 2018.1.2, with the latest version of the plugin. Is this a bug, or what am I doing wrong in configuring my cloud profiles?

**Comment by paksv** [comment]
Looks like it was fixed by 64436a70578331f67d08248cb9cf2c3949a9e57e. Haven't yet ported it to branch, though
