### ISSUE TITLE
The plugin should restart self if have an error. 

### ISSUE THREAD

**Issue by Tsovak** [JetBrains/teamcity-kubernetes-plugin#43]
If something goes wrong the plugin just displays an error and you need to restart the TC Server. 
if you delete deployment, if connection lost, if you have a SocketTimeoutException once. 

Will be better to add retry ability. 
For example, if you had a SocketTimeoutException error, then the plugin should try one more time. 

Now the plugin fails if something going wrong.

**Comment by paksv** [comment]
actually, disabling and reenabling the profile should help as well.

**Comment by paksv** [comment]
Closed in favor of #42 (earlier one)

**Comment by Tsovak** [comment]
actually, after disabling/reenabling the plugin you should restart the TC

**Comment by paksv** [comment]
@Tsovak  you don't have to disable/enable the plugin, just the cloud profile
